apiVersion: v1
kind: Pod
metadata:
 name: control-pod-zbc
spec:
 containers:
 - name: data-loader
   image: ubuntu
   command: ["sleep", "infinity"]
   resources:
    requests:
     cpu: 1
     memory: "1Gi"
    limits:
     cpu: 1
     memory: "1Gi"
   volumeMounts:
   - mountPath: /mnt/ceph_rbd
     name: volume
 volumes:
 - name: volume
   persistentVolumeClaim:
    claimName: platyus-pvc