apiVersion: v1
kind: Pod
metadata:
 name: lm-pod-zbc
spec:
 restartPolicy: Never
 containers:
 - name: lm-con
   image: ghcr.io/dtennant/lm-bwatch:0.1
   # command: ["bash"]
   command: ["sleep", "infinity"]
   # args: ["/mnt/ceph_rbd/example_pytorch_code.py"]
   workingDir: /mnt/ceph_rbd/LLaVA-2
   volumeMounts:
   - mountPath: /mnt/ceph_rbd
     name: volume
   resources:
    requests:
     cpu: 32
     memory: "96Gi"
    limits:
     cpu: 48
     memory: "128Gi"
     nvidia.com/gpu: 1
 nodeSelector:
  # nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB-MIG-1g.5gb
  nvidia.com/gpu.product: NVIDIA-A100-SXM4-80GB
 volumes:
 - name: volume
   persistentVolumeClaim:
    claimName: platyus-pvc